name: Lighthouse Audit

on:
  push:
    branches:
      - master

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install -g lighthouse

      - name: Run Lighthouse
        run: |
          lighthouse --no-enable-error-reporting --chrome-flags="--headless --disable-gpu" https://www.npmjs.com/package/@spotify/lighthouse-audit-service --output json html --output-path=./.lighthouseci/one-platform-test-env

      # - name: Archive Reports
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: lighthouse-reports
      #     path: .lighthouseci/one-platform-test-env
